version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: datalake
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: datalake
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    restart: always

  streamlit:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DB=datalake
      - DATABASE_HOST=postgres

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: C:/Users/leona/Projects/datalake
      o: bind
